# Generated by Django 5.1.3 on 2024-11-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
        ),
    ]
