# Generated by Django 5.1.3 on 2024-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_prizemoney_fourthtotenth_prize_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="regLast",
            new_name="registration_LastDate",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="regLink",
            new_name="registration_Link",
        ),
        migrations.AddField(
            model_name="events",
            name="registration_fee",
            field=models.CharField(default="", max_length=10),
        ),
    ]
