# Generated by Django 5.1.3 on 2024-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_rename_reglast_events_registration_lastdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeline",
            name="timeline_01",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="timeline_02",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="timeline_03",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="timeline_04",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="timeline_05",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="timeline_06",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="timeline_07",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="timeline_08",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="timeline_09",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="timeline_10",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
