# Generated by Django 5.1.3 on 2024-11-14 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_timeline_timeline_01_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="eventInformations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Eligibility", models.CharField(max_length=100)),
                ("teams", models.CharField(max_length=100)),
                (
                    "problem_setter",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("location", models.CharField(max_length=100)),
                ("eventDate", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.events"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="eventRules",
        ),
    ]
