# Generated by Django 5.1.3 on 2024-11-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_eventinformations_delete_eventrules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventinformations",
            name="teams",
        ),
        migrations.AddField(
            model_name="eventinformations",
            name="individual_rule",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="eventinformations",
            name="teams_rule",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
