# Generated by Django 5.1.3 on 2024-11-14 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_groupcriterias_registrationcriterias"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualCriterias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Individual_criteria_01",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Individual_criteria_02",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Individual_criteria_03",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Individual_criteria_04",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Individual_criteria_05",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Individual_criteria_06",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Individual_criteria_07",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Individual_criteria_08",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Individual_criteria_09",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "Individual_criteria_10",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.events"
                    ),
                ),
            ],
        ),
    ]
