# Generated by Django 5.1.3 on 2024-11-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_individualcriterias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prizemoney",
            name="eight_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prizemoney",
            name="fifth_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prizemoney",
            name="first_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prizemoney",
            name="fourth_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prizemoney",
            name="nineth_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prizemoney",
            name="second_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prizemoney",
            name="seventh_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prizemoney",
            name="tenth_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="prizemoney",
            name="third_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
