# Generated by Django 5.1.3 on 2024-11-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_prizemoney_eight_prize_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prizemoney",
            name="sixth_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
