# Generated by Django 5.1.3 on 2024-11-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_competitionsyllabus"),
    ]

    operations = [
        migrations.AddField(
            model_name="prizemoney",
            name="Eleventh_to_Twenty_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="prizemoney",
            name="Twentyoneth_to_Fiftyth_prize",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
