# Generated by Django 5.1.3 on 2024-11-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_prizemoney_eleventh_to_twenty_prize_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluationcriterias",
            name="event",
        ),
        migrations.RemoveField(
            model_name="groupcriterias",
            name="event",
        ),
        migrations.RemoveField(
            model_name="individualcriterias",
            name="event",
        ),
        migrations.RemoveField(
            model_name="registrationcriterias",
            name="event",
        ),
        migrations.DeleteModel(
            name="BonusCriterias",
        ),
        migrations.DeleteModel(
            name="EvaluationCriterias",
        ),
        migrations.DeleteModel(
            name="groupCriterias",
        ),
        migrations.DeleteModel(
            name="IndividualCriterias",
        ),
        migrations.DeleteModel(
            name="RegistrationCriterias",
        ),
    ]
