# Generated by Django 5.1.3 on 2024-11-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_remove_evaluationcriterias_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="guidelines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guideline_Name", models.CharField(max_length=100)),
                ("guideline_pdf", models.FileField(upload_to="")),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.events"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="competitionSyllabus",
        ),
    ]
